In [12]:
import pandas as pd
import numpy as np
from langchain_openai import OpenAIEmbeddings
import os
from langchain_community.vectorstores import Chroma
import time
from langchain_community.embeddings import HuggingFaceEmbeddings

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [3]:
df=pd.read_csv("data/data_gempa_preprocessed.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157332 entries, 0 to 157331
Data columns (total 15 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id                   157332 non-null  object
 1   province_id          157332 non-null  object
 2   place                157332 non-null  object
 3   time                 157332 non-null  object
 4   date                 157332 non-null  object
 5   month                157332 non-null  int64
 6   month_name           157332 non-null  object
 7   year                 157332 non-null  int64
 8   latitude             157332 non-null  float64
 9   longitude            157332 non-null  float64
 10  magnitude            157332 non-null  float64
 11  depth                157332 non-null  float64
 12  depth_category       157332 non-null  object
 13  fault_megathrust_id  12916 non-null   object
 14  Unnamed: 14          0 non-null       float64
dtypes: float64(5), int64(2), object(8)
memory usage: 18.0+ MB

In [4]:

df["time"] = pd.to_datetime(df["time"], errors="coerce")
df = df.dropna(subset=["time"])
df["time"].dtype

C:\Users\calys\AppData\Local\Temp\ipykernel_21512\1419726095.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["time"] = pd.to_datetime(df["time"], errors="coerce")

dtype('<M8[ns]')

In [5]:
def create_event_text(row):
    date_str = row["time"].strftime("%d %B %Y")
    time_str = row["time"].strftime("%H:%M")
    
    text = (
        f"Pada tanggal {date_str} pukul {time_str} WIB terjadi gempa bumi "
        f"di Provinsi {row['place']} dengan magnitudo {row['magnitude']} "
        f"dan kedalaman {row['depth']} km. "
        f"Gempa ini termasuk gempa {row['depth_category']} "
        f"dan berlokasi pada koordinat lintang {row['latitude']} "
        f"dan bujur {row['longitude']}."
    )
    
    return text

In [6]:
df["event_text"] = df.apply(create_event_text, axis=1)
df[["event_text"]].head(10)

                                                                                                                                                                                                                                          event_text
2        Pada tanggal 23 December 2025 pukul 22:53 WIB terjadi gempa bumi di Provinsi Sulawesi Selatan dengan magnitudo 4.7 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -7.8936 dan bujur 117.8591.
4                    Pada tanggal 23 December 2025 pukul 16:23 WIB terjadi gempa bumi di Provinsi Papua dengan magnitudo 6.3 dan kedalaman 33.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -2.9934 dan bujur 139.372.
5              Pada tanggal 23 December 2025 pukul 18:20 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.5 dan kedalaman 154.099 km. Gempa ini termasuk gempa menengah dan berlokasi pada koordinat lintang -7.3765 dan bujur 128.6381.
9      Pada tanggal 23 December 2025 pukul 12:50 WIB terjadi gempa bumi di Provinsi Nusa Tenggara Timur dengan magnitudo 4.5 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -9.7104 dan bujur 124.905.
15     Pada tanggal 23 December 2025 pukul 00:52 WIB terjadi gempa bumi di Provinsi Sulawesi Selatan dengan magnitudo 4.6 dan kedalaman 15.846 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -7.9232 dan bujur 117.8425.
16            Pada tanggal 23 December 2025 pukul 07:44 WIB terjadi gempa bumi di Provinsi Maluku Utara dengan magnitudo 4.9 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang 1.3767 dan bujur 128.2814.
17        Pada tanggal 23 December 2025 pukul 09:16 WIB terjadi gempa bumi di Provinsi Sulawesi Utara dengan magnitudo 4.9 dan kedalaman 56.326 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang 0.4641 dan bujur 125.3686.
26                    Pada tanggal 23 December 2025 pukul 20:45 WIB terjadi gempa bumi di Provinsi Aceh dengan magnitudo 4.5 dan kedalaman 9.334 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang 5.9749 dan bujur 94.8546.
27  Pada tanggal 23 December 2025 pukul 18:55 WIB terjadi gempa bumi di Provinsi Nusa Tenggara Timur dengan magnitudo 4.7 dan kedalaman 10.354 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -7.1442 dan bujur 122.3963.
28               Pada tanggal 23 December 2025 pukul 17:41 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.5 dan kedalaman 31.331 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -7.4114 dan bujur 130.3421.

In [7]:
df[["event_text"]].head(10)

                                                                                                                                                                                                                                          event_text
2        Pada tanggal 23 December 2025 pukul 22:53 WIB terjadi gempa bumi di Provinsi Sulawesi Selatan dengan magnitudo 4.7 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -7.8936 dan bujur 117.8591.
4                    Pada tanggal 23 December 2025 pukul 16:23 WIB terjadi gempa bumi di Provinsi Papua dengan magnitudo 6.3 dan kedalaman 33.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -2.9934 dan bujur 139.372.
5              Pada tanggal 23 December 2025 pukul 18:20 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.5 dan kedalaman 154.099 km. Gempa ini termasuk gempa menengah dan berlokasi pada koordinat lintang -7.3765 dan bujur 128.6381.
9      Pada tanggal 23 December 2025 pukul 12:50 WIB terjadi gempa bumi di Provinsi Nusa Tenggara Timur dengan magnitudo 4.5 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -9.7104 dan bujur 124.905.
15     Pada tanggal 23 December 2025 pukul 00:52 WIB terjadi gempa bumi di Provinsi Sulawesi Selatan dengan magnitudo 4.6 dan kedalaman 15.846 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -7.9232 dan bujur 117.8425.
16            Pada tanggal 23 December 2025 pukul 07:44 WIB terjadi gempa bumi di Provinsi Maluku Utara dengan magnitudo 4.9 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang 1.3767 dan bujur 128.2814.
17        Pada tanggal 23 December 2025 pukul 09:16 WIB terjadi gempa bumi di Provinsi Sulawesi Utara dengan magnitudo 4.9 dan kedalaman 56.326 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang 0.4641 dan bujur 125.3686.
26                    Pada tanggal 23 December 2025 pukul 20:45 WIB terjadi gempa bumi di Provinsi Aceh dengan magnitudo 4.5 dan kedalaman 9.334 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang 5.9749 dan bujur 94.8546.
27  Pada tanggal 23 December 2025 pukul 18:55 WIB terjadi gempa bumi di Provinsi Nusa Tenggara Timur dengan magnitudo 4.7 dan kedalaman 10.354 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -7.1442 dan bujur 122.3963.
28               Pada tanggal 23 December 2025 pukul 17:41 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.5 dan kedalaman 31.331 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -7.4114 dan bujur 130.3421.

In [8]:
df["metadata"] = df.apply(
    lambda row: {
        "province": row["place"],
        "date": str(row["date"]),
        "year": int(row["year"]),
        "month": int(row["month"]),
        "depth_category": row["depth_category"],
        "magnitude": row["magnitude"]
    },
    axis=1
)

In [9]:
documents = [
    {
        "text": row["event_text"],
        "metadata": row["metadata"]
    }
    for _, row in df.iterrows()
]

In [10]:
documents

[{'text': 'Pada tanggal 23 December 2025 pukul 22:53 WIB terjadi gempa bumi di Provinsi Sulawesi Selatan dengan magnitudo 4.7 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -7.8936 dan bujur 117.8591.',
  'metadata': {'province': 'Sulawesi Selatan',
   'date': '1/1/2024',
   'year': 2024,
   'month': 1,
   'depth_category': 'dangkal',
   'magnitude': 4.7}},
 {'text': 'Pada tanggal 23 December 2025 pukul 16:23 WIB terjadi gempa bumi di Provinsi Papua dengan magnitudo 6.3 dan kedalaman 33.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -2.9934 dan bujur 139.372.',
  'metadata': {'province': 'Papua',
   'date': '12/30/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'dangkal',
   'magnitude': 6.3}},
 {'text': 'Pada tanggal 23 December 2025 pukul 18:20 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.5 dan kedalaman 154.099 km. Gempa ini termasuk gempa menengah dan berlokasi pada koordinat lintang -7.3765 dan bujur 128.6381.',
  'metadata': {'province': 'Maluku',
   'date': '12/29/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'menengah',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 23 December 2025 pukul 12:50 WIB terjadi gempa bumi di Provinsi Nusa Tenggara Timur dengan magnitudo 4.5 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -9.7104 dan bujur 124.905.',
  'metadata': {'province': 'Nusa Tenggara Timur',
   'date': '12/26/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'dangkal',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 23 December 2025 pukul 00:52 WIB terjadi gempa bumi di Provinsi Sulawesi Selatan dengan magnitudo 4.6 dan kedalaman 15.846 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -7.9232 dan bujur 117.8425.',
  'metadata': {'province': 'Sulawesi Selatan',
   'date': '12/24/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'dangkal',
   'magnitude': 4.6}},
 {'text': 'Pada tanggal 23 December 2025 pukul 07:44 WIB terjadi gempa bumi di Provinsi Maluku Utara dengan magnitudo 4.9 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang 1.3767 dan bujur 128.2814.',
  'metadata': {'province': 'Maluku Utara',
   'date': '12/23/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'dangkal',
   'magnitude': 4.9}},
 {'text': 'Pada tanggal 23 December 2025 pukul 09:16 WIB terjadi gempa bumi di Provinsi Sulawesi Utara dengan magnitudo 4.9 dan kedalaman 56.326 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang 0.4641 dan bujur 125.3686.',
  'metadata': {'province': 'Sulawesi Utara',
   'date': '12/23/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'dangkal',
   'magnitude': 4.9}},
 {'text': 'Pada tanggal 23 December 2025 pukul 20:45 WIB terjadi gempa bumi di Provinsi Aceh dengan magnitudo 4.5 dan kedalaman 9.334 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang 5.9749 dan bujur 94.8546.',
  'metadata': {'province': 'Aceh',
   'date': '12/18/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'dangkal',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 23 December 2025 pukul 18:55 WIB terjadi gempa bumi di Provinsi Nusa Tenggara Timur dengan magnitudo 4.7 dan kedalaman 10.354 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -7.1442 dan bujur 122.3963.',
  'metadata': {'province': 'Nusa Tenggara Timur',
   'date': '12/18/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'dangkal',
   'magnitude': 4.7}},
 {'text': 'Pada tanggal 23 December 2025 pukul 17:41 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.5 dan kedalaman 31.331 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -7.4114 dan bujur 130.3421.',
  'metadata': {'province': 'Maluku',
   'date': '12/18/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'dangkal',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 23 December 2025 pukul 02:09 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.9 dan kedalaman 158.377 km. Gempa ini termasuk gempa menengah dan berlokasi pada koordinat lintang -6.8918 dan bujur 129.5256.',
  'metadata': {'province': 'Maluku',
   'date': '12/15/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'menengah',
   'magnitude': 4.9}},
 {'text': 'Pada tanggal 23 December 2025 pukul 05:49 WIB terjadi gempa bumi di Provinsi Sulawesi Utara dengan magnitudo 5.0 dan kedalaman 104.287 km. Gempa ini termasuk gempa menengah dan berlokasi pada koordinat lintang 0.1199 dan bujur 124.0114.',
  'metadata': {'province': 'Sulawesi Utara',
   'date': '12/14/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'menengah',
   'magnitude': 5.0}},
 {'text': 'Pada tanggal 23 December 2025 pukul 08:56 WIB terjadi gempa bumi di Provinsi Aceh dengan magnitudo 4.5 dan kedalaman 29.597 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang 2.0407 dan bujur 96.7775.',
  'metadata': {'province': 'Aceh',
   'date': '12/13/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'dangkal',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 23 December 2025 pukul 16:39 WIB terjadi gempa bumi di Provinsi Riau dengan magnitudo 5.0 dan kedalaman 255.387 km. Gempa ini termasuk gempa menengah dan berlokasi pada koordinat lintang -0.4441 dan bujur 101.3587.',
  'metadata': {'province': 'Riau',
   'date': '12/11/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'menengah',
   'magnitude': 5.0}},
 {'text': 'Pada tanggal 23 December 2025 pukul 03:41 WIB terjadi gempa bumi di Provinsi Sumatera Barat dengan magnitudo 4.6 dan kedalaman 35.243 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -2.6009 dan bujur 99.9941.',
  'metadata': {'province': 'Sumatera Barat',
   'date': '12/8/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'dangkal',
   'magnitude': 4.6}},
 {'text': 'Pada tanggal 23 December 2025 pukul 09:20 WIB terjadi gempa bumi di Provinsi Maluku Utara dengan magnitudo 5.0 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -1.1405 dan bujur 126.8473.',
  'metadata': {'province': 'Maluku Utara',
   'date': '12/7/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'dangkal',
   'magnitude': 5.0}},
 {'text': 'Pada tanggal 23 December 2025 pukul 01:27 WIB terjadi gempa bumi di Provinsi Sulawesi Utara dengan magnitudo 4.6 dan kedalaman 41.408 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang 3.1941 dan bujur 126.6826.',
  'metadata': {'province': 'Sulawesi Utara',
   'date': '12/6/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'dangkal',
   'magnitude': 4.6}},
 {'text': 'Pada tanggal 23 December 2025 pukul 21:33 WIB terjadi gempa bumi di Provinsi Sulawesi Utara dengan magnitudo 4.8 dan kedalaman 46.238 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang 3.5472 dan bujur 126.8715.',
  'metadata': {'province': 'Sulawesi Utara',
   'date': '12/4/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'dangkal',
   'magnitude': 4.8}},
 {'text': 'Pada tanggal 23 December 2025 pukul 01:00 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 5.5 dan kedalaman 117.236 km. Gempa ini termasuk gempa menengah dan berlokasi pada koordinat lintang -7.0345 dan bujur 129.6876.',
  'metadata': {'province': 'Maluku',
   'date': '12/2/2023',
   'year': 2023,
   'month': 12,
   'depth_category': 'menengah',
   'magnitude': 5.5}},
 {'text': 'Pada tanggal 23 December 2025 pukul 08:41 WIB terjadi gempa bumi di Provinsi Nusa Tenggara Timur dengan magnitudo 4.5 dan kedalaman 175.981 km. Gempa ini termasuk gempa menengah dan berlokasi pada koordinat lintang -8.0933 dan bujur 119.8861.',
  'metadata': {'province': 'Nusa Tenggara Timur',
   'date': '11/30/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'menengah',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 23 December 2025 pukul 02:12 WIB terjadi gempa bumi di Provinsi Papua dengan magnitudo 4.5 dan kedalaman 34.463 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -3.4719 dan bujur 139.7516.',
  'metadata': {'province': 'Papua',
   'date': '11/29/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 23 December 2025 pukul 19:27 WIB terjadi gempa bumi di Provinsi Maluku Utara dengan magnitudo 4.5 dan kedalaman 229.969 km. Gempa ini termasuk gempa menengah dan berlokasi pada koordinat lintang 2.6829 dan bujur 128.5208.',
  'metadata': {'province': 'Maluku Utara',
   'date': '11/28/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'menengah',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 23 December 2025 pukul 06:33 WIB terjadi gempa bumi di Provinsi Papua dengan magnitudo 4.6 dan kedalaman 26.899 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -2.3376 dan bujur 139.1478.',
  'metadata': {'province': 'Papua',
   'date': '11/26/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 4.6}},
 {'text': 'Pada tanggal 23 December 2025 pukul 21:47 WIB terjadi gempa bumi di Provinsi Maluku Utara dengan magnitudo 4.9 dan kedalaman 148.42 km. Gempa ini termasuk gempa menengah dan berlokasi pada koordinat lintang 1.3425 dan bujur 127.9982.',
  'metadata': {'province': 'Maluku Utara',
   'date': '11/26/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'menengah',
   'magnitude': 4.9}},
 {'text': 'Pada tanggal 23 December 2025 pukul 21:50 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.6 dan kedalaman 7.439 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -6.1992 dan bujur 129.8018.',
  'metadata': {'province': 'Maluku',
   'date': '11/24/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 4.6}},
 {'text': 'Pada tanggal 23 December 2025 pukul 12:14 WIB terjadi gempa bumi di Provinsi Papua dengan magnitudo 5.2 dan kedalaman 17.009 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -0.5476 dan bujur 135.8426.',
  'metadata': {'province': 'Papua',
   'date': '11/21/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 5.2}},
 {'text': 'Pada tanggal 23 December 2025 pukul 04:54 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.6 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -6.2753 dan bujur 129.5428.',
  'metadata': {'province': 'Maluku',
   'date': '11/20/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 4.6}},
 {'text': 'Pada tanggal 23 December 2025 pukul 01:33 WIB terjadi gempa bumi di Provinsi Sumatera Barat dengan magnitudo 4.9 dan kedalaman 23.026 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -2.9945 dan bujur 100.0625.',
  'metadata': {'province': 'Sumatera Barat',
   'date': '11/18/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 4.9}},
 {'text': 'Pada tanggal 23 December 2025 pukul 02:18 WIB terjadi gempa bumi di Provinsi Papua dengan magnitudo 5.2 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -2.4108 dan bujur 138.8023.',
  'metadata': {'province': 'Papua',
   'date': '11/17/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 5.2}},
 {'text': 'Pada tanggal 23 December 2025 pukul 21:48 WIB terjadi gempa bumi di Provinsi Papua Pegunungan dengan magnitudo 5.1 dan kedalaman 93.322 km. Gempa ini termasuk gempa menengah dan berlokasi pada koordinat lintang -3.785 dan bujur 138.674.',
  'metadata': {'province': 'Papua Pegunungan',
   'date': '11/16/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'menengah',
   'magnitude': 5.1}},
 {'text': 'Pada tanggal 23 December 2025 pukul 23:36 WIB terjadi gempa bumi di Provinsi Nusa Tenggara Timur dengan magnitudo 4.5 dan kedalaman 116.744 km. Gempa ini termasuk gempa menengah dan berlokasi pada koordinat lintang -8.8087 dan bujur 124.09.',
  'metadata': {'province': 'Nusa Tenggara Timur',
   'date': '11/15/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'menengah',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 23 December 2025 pukul 11:04 WIB terjadi gempa bumi di Provinsi Bengkulu dengan magnitudo 4.8 dan kedalaman 56.133 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -3.5315 dan bujur 101.4988.',
  'metadata': {'province': 'Bengkulu',
   'date': '11/15/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 4.8}},
 {'text': 'Pada tanggal 23 December 2025 pukul 19:55 WIB terjadi gempa bumi di Provinsi Sulawesi Utara dengan magnitudo 4.6 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang 1.3856 dan bujur 125.7397.',
  'metadata': {'province': 'Sulawesi Utara',
   'date': '11/14/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 4.6}},
 {'text': 'Pada tanggal 23 December 2025 pukul 21:47 WIB terjadi gempa bumi di Provinsi Sulawesi Utara dengan magnitudo 4.6 dan kedalaman 75.656 km. Gempa ini termasuk gempa menengah dan berlokasi pada koordinat lintang 4.9181 dan bujur 126.4698.',
  'metadata': {'province': 'Sulawesi Utara',
   'date': '11/14/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'menengah',
   'magnitude': 4.6}},
 {'text': 'Pada tanggal 23 December 2025 pukul 17:24 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.5 dan kedalaman 9.991 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -6.2657 dan bujur 129.716.',
  'metadata': {'province': 'Maluku',
   'date': '11/14/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 23 December 2025 pukul 22:51 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 5.2 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -5.8841 dan bujur 130.1522.',
  'metadata': {'province': 'Maluku',
   'date': '11/14/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 5.2}},
 {'text': 'Pada tanggal 23 December 2025 pukul 06:16 WIB terjadi gempa bumi di Provinsi Nusa Tenggara Timur dengan magnitudo 5.2 dan kedalaman 42.657 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -9.9173 dan bujur 123.699.',
  'metadata': {'province': 'Nusa Tenggara Timur',
   'date': '11/12/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 5.2}},
 {'text': 'Pada tanggal 23 December 2025 pukul 07:29 WIB terjadi gempa bumi di Provinsi Nusa Tenggara Timur dengan magnitudo 4.6 dan kedalaman 35.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -10.1256 dan bujur 123.6626.',
  'metadata': {'province': 'Nusa Tenggara Timur',
   'date': '11/11/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 4.6}},
 {'text': 'Pada tanggal 23 December 2025 pukul 10:53 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.5 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -6.1155 dan bujur 130.032.',
  'metadata': {'province': 'Maluku',
   'date': '11/11/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 23 December 2025 pukul 11:31 WIB terjadi gempa bumi di Provinsi Papua dengan magnitudo 4.7 dan kedalaman 26.513 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -1.9507 dan bujur 139.3305.',
  'metadata': {'province': 'Papua',
   'date': '11/11/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 4.7}},
 {'text': 'Pada tanggal 23 December 2025 pukul 20:12 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 5.6 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -6.1476 dan bujur 130.1327.',
  'metadata': {'province': 'Maluku',
   'date': '11/10/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 5.6}},
 {'text': 'Pada tanggal 23 December 2025 pukul 13:35 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 5.3 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -6.0958 dan bujur 130.1099.',
  'metadata': {'province': 'Maluku',
   'date': '11/10/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 5.3}},
 {'text': 'Pada tanggal 23 December 2025 pukul 08:55 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.9 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -6.1227 dan bujur 130.1012.',
  'metadata': {'province': 'Maluku',
   'date': '11/10/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 4.9}},
 {'text': 'Pada tanggal 23 December 2025 pukul 05:58 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 5.0 dan kedalaman 8.578 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -6.104 dan bujur 129.9405.',
  'metadata': {'province': 'Maluku',
   'date': '11/10/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 5.0}},
 {'text': 'Pada tanggal 23 December 2025 pukul 22:56 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.5 dan kedalaman 112.072 km. Gempa ini termasuk gempa menengah dan berlokasi pada koordinat lintang -7.0405 dan bujur 129.6776.',
  'metadata': {'province': 'Maluku',
   'date': '11/10/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'menengah',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 23 December 2025 pukul 18:43 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.8 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -5.9168 dan bujur 129.9853.',
  'metadata': {'province': 'Maluku',
   'date': '11/10/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 4.8}},
 {'text': 'Pada tanggal 23 December 2025 pukul 11:03 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.5 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -5.8638 dan bujur 130.0319.',
  'metadata': {'province': 'Maluku',
   'date': '11/10/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 23 December 2025 pukul 11:18 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.5 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -6.0168 dan bujur 130.003.',
  'metadata': {'province': 'Maluku',
   'date': '11/10/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 23 December 2025 pukul 13:18 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.5 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -5.6651 dan bujur 130.2065.',
  'metadata': {'province': 'Maluku',
   'date': '11/10/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 4.5}},
 {'text': 'Pada tanggal 23 December 2025 pukul 12:56 WIB terjadi gempa bumi di Provinsi Maluku dengan magnitudo 4.6 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -6.3451 dan bujur 129.5232.',
  'metadata': {'province': 'Maluku',
   'date': '11/9/2023',
   'year': 2023,
   'month': 11,
   'depth_category': 'dangkal',
   'magnitude': 4.6}},

In [11]:
texts = [doc["text"] for doc in documents]
metadatas = [doc["metadata"] for doc in documents]

embeddings api openai

In [36]:
os.environ["OPENAI_API_KEY"] = "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"
embeddings = OpenAIEmbeddings(
    model="text-embedding-3-small"
)

In [35]:
vectorstore = Chroma(
    embedding_function=embeddings,
    persist_directory="chroma_gempa_db"
)

In [37]:
BATCH_SIZE = 5        # SANGAT kecil
BASE_SLEEP = 6        # detik
MAX_CHARS = 1200      # aman utk token
MAX_RETRY = 5

import random
from openai import RateLimitError

def safe_ingest(vectorstore, texts, metadatas):
    total = len(texts)
    batch_num = 0

    for i in range(0, total, BATCH_SIZE):
        batch_num += 1

        batch_texts = [
            t[:MAX_CHARS] for t in texts[i:i + BATCH_SIZE]
        ]
        batch_metadatas = metadatas[i:i + BATCH_SIZE]

        retry = 0
        while retry <= MAX_RETRY:
            try:
                vectorstore.add_texts(
                    texts=batch_texts,
                    metadatas=batch_metadatas
                )

                print(f"✅ Batch {batch_num} sukses")
                break

            except RateLimitError:
                retry += 1
                sleep_time = BASE_SLEEP * (2 ** retry) + random.uniform(1, 3)
                print(f"⏳ Rate limit! Retry {retry}, tidur {sleep_time:.1f}s")
                time.sleep(sleep_time)

        time.sleep(BASE_SLEEP)

In [ ]:
safe_ingest(
    vectorstore=vectorstore,
    texts=texts,
    metadatas=metadatas
)

⏳ Rate limit! Retry 1, tidur 13.7s
⏳ Rate limit! Retry 2, tidur 25.0s
⏳ Rate limit! Retry 3, tidur 51.0s
⏳ Rate limit! Retry 4, tidur 97.3s
⏳ Rate limit! Retry 5, tidur 194.9s
⏳ Rate limit! Retry 6, tidur 386.5s

embeddings lokal

In [13]:
embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

C:\Users\calys\AppData\Local\Temp\ipykernel_21512\1474760240.py:1: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the `langchain-huggingface package and should be used instead. To use it run `pip install -U `langchain-huggingface` and import as `from `langchain_huggingface import HuggingFaceEmbeddings``.
  embeddings = HuggingFaceEmbeddings(
e:\COOLYEAH\PA\gempa\venv\lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\calys\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

In [14]:
vectorstore = Chroma(
    embedding_function=embeddings,
    persist_directory="chroma_gempa_db"
)

C:\Users\calys\AppData\Local\Temp\ipykernel_21512\2493910305.py:1: LangChainDeprecationWarning: The class `Chroma` was deprecated in LangChain 0.2.9 and will be removed in 1.0. An updated version of the class exists in the `langchain-chroma package and should be used instead. To use it run `pip install -U `langchain-chroma` and import as `from `langchain_chroma import Chroma``.
  vectorstore = Chroma(

In [15]:
batch_size = 50

for i in range(0, len(texts), batch_size):
    vectorstore.add_texts(
        texts=texts[i:i+batch_size],
        metadatas=metadatas[i:i+batch_size]
    )
    print(f"Batch {i//batch_size + 1} masuk")

vectorstore.persist()

Batch 1 masuk
Batch 2 masuk
Batch 3 masuk
Batch 4 masuk
Batch 5 masuk
Batch 6 masuk
Batch 7 masuk
Batch 8 masuk
Batch 9 masuk
Batch 10 masuk
Batch 11 masuk
Batch 12 masuk
Batch 13 masuk
Batch 14 masuk
Batch 15 masuk
Batch 16 masuk
Batch 17 masuk
Batch 18 masuk
Batch 19 masuk
Batch 20 masuk
Batch 21 masuk
Batch 22 masuk
Batch 23 masuk
Batch 24 masuk
Batch 25 masuk
Batch 26 masuk
Batch 27 masuk
Batch 28 masuk
Batch 29 masuk
Batch 30 masuk
Batch 31 masuk
Batch 32 masuk
Batch 33 masuk
Batch 34 masuk
Batch 35 masuk
Batch 36 masuk
Batch 37 masuk
Batch 38 masuk
Batch 39 masuk
Batch 40 masuk
Batch 41 masuk
Batch 42 masuk
Batch 43 masuk
Batch 44 masuk
Batch 45 masuk
Batch 46 masuk
Batch 47 masuk
Batch 48 masuk
Batch 49 masuk
Batch 50 masuk
Batch 51 masuk
Batch 52 masuk
Batch 53 masuk
Batch 54 masuk
Batch 55 masuk
Batch 56 masuk
Batch 57 masuk
Batch 58 masuk
Batch 59 masuk
Batch 60 masuk
Batch 61 masuk
Batch 62 masuk
Batch 63 masuk
Batch 64 masuk
Batch 65 masuk
Batch 66 masuk
Batch 67 masuk
Batch 68 masuk
Batch 69 masuk
Batch 70 masuk
Batch 71 masuk
Batch 72 masuk
Batch 73 masuk
Batch 74 masuk
Batch 75 masuk
Batch 76 masuk
Batch 77 masuk
Batch 78 masuk
Batch 79 masuk
Batch 80 masuk
Batch 81 masuk
Batch 82 masuk
Batch 83 masuk
Batch 84 masuk
Batch 85 masuk
Batch 86 masuk
Batch 87 masuk
Batch 88 masuk
Batch 89 masuk
Batch 90 masuk
Batch 91 masuk
Batch 92 masuk
Batch 93 masuk
Batch 94 masuk
Batch 95 masuk
Batch 96 masuk
Batch 97 masuk
Batch 98 masuk
Batch 99 masuk
Batch 100 masuk
Batch 101 masuk
Batch 102 masuk
Batch 103 masuk
Batch 104 masuk
Batch 105 masuk
Batch 106 masuk
Batch 107 masuk
Batch 108 masuk
Batch 109 masuk
Batch 110 masuk
Batch 111 masuk
Batch 112 masuk
Batch 113 masuk
Batch 114 masuk
Batch 115 masuk
Batch 116 masuk
Batch 117 masuk
Batch 118 masuk
Batch 119 masuk
Batch 120 masuk
Batch 121 masuk
Batch 122 masuk
Batch 123 masuk
Batch 124 masuk
Batch 125 masuk
Batch 126 masuk
Batch 127 masuk
Batch 128 masuk
Batch 129 masuk
Batch 130 masuk
Batch 131 masuk
Batch 132 masuk
Batch 133 masuk
Batch 134 masuk
Batch 135 masuk
Batch 136 masuk
Batch 137 masuk
Batch 138 masuk
Batch 139 masuk
Batch 140 masuk
Batch 141 masuk
Batch 142 masuk
Batch 143 masuk
Batch 144 masuk
Batch 145 masuk
Batch 146 masuk
Batch 147 masuk
Batch 148 masuk
Batch 149 masuk
Batch 150 masuk
Batch 151 masuk
Batch 152 masuk
Batch 153 masuk
Batch 154 masuk
Batch 155 masuk
Batch 156 masuk
Batch 157 masuk
Batch 158 masuk
Batch 159 masuk
Batch 160 masuk
Batch 161 masuk
Batch 162 masuk
Batch 163 masuk
Batch 164 masuk
Batch 165 masuk
Batch 166 masuk
Batch 167 masuk
Batch 168 masuk
Batch 169 masuk
Batch 170 masuk
Batch 171 masuk
Batch 172 masuk
Batch 173 masuk
Batch 174 masuk
Batch 175 masuk
Batch 176 masuk
Batch 177 masuk
Batch 178 masuk
Batch 179 masuk
Batch 180 masuk
Batch 181 masuk
Batch 182 masuk
Batch 183 masuk
Batch 184 masuk
Batch 185 masuk
Batch 186 masuk
Batch 187 masuk
Batch 188 masuk
Batch 189 masuk
Batch 190 masuk
Batch 191 masuk
Batch 192 masuk
Batch 193 masuk
Batch 194 masuk
Batch 195 masuk
Batch 196 masuk
Batch 197 masuk
Batch 198 masuk
Batch 199 masuk
Batch 200 masuk
Batch 201 masuk
Batch 202 masuk
Batch 203 masuk
Batch 204 masuk
Batch 205 masuk
Batch 206 masuk
Batch 207 masuk
Batch 208 masuk
Batch 209 masuk
Batch 210 masuk
Batch 211 masuk
Batch 212 masuk
Batch 213 masuk
Batch 214 masuk
Batch 215 masuk
Batch 216 masuk
Batch 217 masuk
Batch 218 masuk
Batch 219 masuk
Batch 220 masuk
Batch 221 masuk
Batch 222 masuk
Batch 223 masuk
Batch 224 masuk
Batch 225 masuk
Batch 226 masuk
Batch 227 masuk
Batch 228 masuk
Batch 229 masuk
Batch 230 masuk
Batch 231 masuk
Batch 232 masuk
Batch 233 masuk
Batch 234 masuk
Batch 235 masuk
Batch 236 masuk
Batch 237 masuk
Batch 238 masuk
Batch 239 masuk
Batch 240 masuk
Batch 241 masuk
Batch 242 masuk
Batch 243 masuk
Batch 244 masuk
Batch 245 masuk
Batch 246 masuk
Batch 247 masuk
Batch 248 masuk
Batch 249 masuk
Batch 250 masuk
Batch 251 masuk
Batch 252 masuk
Batch 253 masuk
Batch 254 masuk
Batch 255 masuk
Batch 256 masuk
Batch 257 masuk
Batch 258 masuk
Batch 259 masuk
Batch 260 masuk
Batch 261 masuk
Batch 262 masuk
Batch 263 masuk
Batch 264 masuk
Batch 265 masuk
Batch 266 masuk
Batch 267 masuk
Batch 268 masuk
Batch 269 masuk
Batch 270 masuk
Batch 271 masuk
Batch 272 masuk
Batch 273 masuk
Batch 274 masuk
Batch 275 masuk
Batch 276 masuk
Batch 277 masuk
Batch 278 masuk
Batch 279 masuk
Batch 280 masuk
Batch 281 masuk
Batch 282 masuk
Batch 283 masuk
Batch 284 masuk
Batch 285 masuk
Batch 286 masuk
Batch 287 masuk
Batch 288 masuk
Batch 289 masuk
Batch 290 masuk
Batch 291 masuk
Batch 292 masuk
Batch 293 masuk
Batch 294 masuk
Batch 295 masuk
Batch 296 masuk
Batch 297 masuk
Batch 298 masuk
Batch 299 masuk
Batch 300 masuk
Batch 301 masuk
Batch 302 masuk
Batch 303 masuk
Batch 304 masuk
Batch 305 masuk
Batch 306 masuk
Batch 307 masuk
Batch 308 masuk
Batch 309 masuk
Batch 310 masuk
Batch 311 masuk
Batch 312 masuk
Batch 313 masuk
Batch 314 masuk
Batch 315 masuk
Batch 316 masuk
Batch 317 masuk
Batch 318 masuk
Batch 319 masuk
Batch 320 masuk
Batch 321 masuk
Batch 322 masuk
Batch 323 masuk
Batch 324 masuk
Batch 325 masuk
Batch 326 masuk
Batch 327 masuk
Batch 328 masuk
Batch 329 masuk
Batch 330 masuk
Batch 331 masuk
Batch 332 masuk
Batch 333 masuk
Batch 334 masuk
Batch 335 masuk
Batch 336 masuk
Batch 337 masuk
Batch 338 masuk
Batch 339 masuk
Batch 340 masuk
Batch 341 masuk
Batch 342 masuk
Batch 343 masuk
Batch 344 masuk
Batch 345 masuk
Batch 346 masuk
Batch 347 masuk
Batch 348 masuk
Batch 349 masuk
Batch 350 masuk
Batch 351 masuk
Batch 352 masuk
Batch 353 masuk
Batch 354 masuk
Batch 355 masuk
Batch 356 masuk
Batch 357 masuk
Batch 358 masuk
Batch 359 masuk
Batch 360 masuk
Batch 361 masuk
Batch 362 masuk
Batch 363 masuk
Batch 364 masuk
Batch 365 masuk
Batch 366 masuk
Batch 367 masuk
Batch 368 masuk
Batch 369 masuk
Batch 370 masuk
Batch 371 masuk
Batch 372 masuk
Batch 373 masuk
Batch 374 masuk
Batch 375 masuk
Batch 376 masuk
Batch 377 masuk
Batch 378 masuk
Batch 379 masuk
Batch 380 masuk
Batch 381 masuk
Batch 382 masuk
Batch 383 masuk
Batch 384 masuk
Batch 385 masuk
Batch 386 masuk
Batch 387 masuk
Batch 388 masuk
Batch 389 masuk
Batch 390 masuk
Batch 391 masuk
Batch 392 masuk
Batch 393 masuk
Batch 394 masuk
Batch 395 masuk
Batch 396 masuk
Batch 397 masuk
Batch 398 masuk
Batch 399 masuk
Batch 400 masuk
Batch 401 masuk
Batch 402 masuk
Batch 403 masuk
Batch 404 masuk
Batch 405 masuk
Batch 406 masuk
Batch 407 masuk
Batch 408 masuk
Batch 409 masuk
Batch 410 masuk
Batch 411 masuk
Batch 412 masuk
Batch 413 masuk
Batch 414 masuk
Batch 415 masuk
Batch 416 masuk
Batch 417 masuk
Batch 418 masuk
Batch 419 masuk
Batch 420 masuk
Batch 421 masuk
Batch 422 masuk
Batch 423 masuk
Batch 424 masuk
Batch 425 masuk
Batch 426 masuk
Batch 427 masuk
Batch 428 masuk
Batch 429 masuk
Batch 430 masuk
Batch 431 masuk
Batch 432 masuk
Batch 433 masuk
Batch 434 masuk
Batch 435 masuk
Batch 436 masuk
Batch 437 masuk
Batch 438 masuk
Batch 439 masuk
Batch 440 masuk
Batch 441 masuk
Batch 442 masuk
Batch 443 masuk
Batch 444 masuk
Batch 445 masuk
Batch 446 masuk
Batch 447 masuk
Batch 448 masuk
Batch 449 masuk
Batch 450 masuk
Batch 451 masuk
Batch 452 masuk
Batch 453 masuk
Batch 454 masuk
Batch 455 masuk
Batch 456 masuk
Batch 457 masuk
Batch 458 masuk
Batch 459 masuk
Batch 460 masuk
Batch 461 masuk
Batch 462 masuk
Batch 463 masuk
Batch 464 masuk
Batch 465 masuk
Batch 466 masuk
Batch 467 masuk
Batch 468 masuk
Batch 469 masuk
Batch 470 masuk
Batch 471 masuk
Batch 472 masuk
Batch 473 masuk
Batch 474 masuk
Batch 475 masuk
Batch 476 masuk
Batch 477 masuk
Batch 478 masuk
Batch 479 masuk
Batch 480 masuk
Batch 481 masuk
Batch 482 masuk
Batch 483 masuk
Batch 484 masuk
Batch 485 masuk
Batch 486 masuk
Batch 487 masuk
Batch 488 masuk
Batch 489 masuk
Batch 490 masuk
Batch 491 masuk
Batch 492 masuk
Batch 493 masuk
Batch 494 masuk
Batch 495 masuk
Batch 496 masuk
Batch 497 masuk
Batch 498 masuk
Batch 499 masuk
Batch 500 masuk
Batch 501 masuk
Batch 502 masuk
Batch 503 masuk
Batch 504 masuk
Batch 505 masuk
Batch 506 masuk
Batch 507 masuk
Batch 508 masuk
Batch 509 masuk
Batch 510 masuk
Batch 511 masuk
Batch 512 masuk
Batch 513 masuk
Batch 514 masuk
Batch 515 masuk
Batch 516 masuk
Batch 517 masuk
Batch 518 masuk
Batch 519 masuk
Batch 520 masuk
Batch 521 masuk
Batch 522 masuk
Batch 523 masuk
Batch 524 masuk
Batch 525 masuk
Batch 526 masuk
Batch 527 masuk
Batch 528 masuk
Batch 529 masuk
Batch 530 masuk
Batch 531 masuk
Batch 532 masuk
Batch 533 masuk
Batch 534 masuk
Batch 535 masuk
Batch 536 masuk
Batch 537 masuk
Batch 538 masuk
Batch 539 masuk
Batch 540 masuk
Batch 541 masuk
Batch 542 masuk
Batch 543 masuk
Batch 544 masuk
Batch 545 masuk
Batch 546 masuk
Batch 547 masuk
Batch 548 masuk
Batch 549 masuk
Batch 550 masuk
Batch 551 masuk
Batch 552 masuk
Batch 553 masuk
Batch 554 masuk
Batch 555 masuk
Batch 556 masuk
Batch 557 masuk
Batch 558 masuk
Batch 559 masuk
Batch 560 masuk
Batch 561 masuk
Batch 562 masuk
Batch 563 masuk
Batch 564 masuk
Batch 565 masuk
Batch 566 masuk
Batch 567 masuk
Batch 568 masuk
Batch 569 masuk
Batch 570 masuk
Batch 571 masuk
Batch 572 masuk
Batch 573 masuk
Batch 574 masuk
Batch 575 masuk
Batch 576 masuk
Batch 577 masuk
Batch 578 masuk
Batch 579 masuk
Batch 580 masuk
Batch 581 masuk
Batch 582 masuk
Batch 583 masuk
Batch 584 masuk
Batch 585 masuk
Batch 586 masuk
Batch 587 masuk
Batch 588 masuk
Batch 589 masuk
Batch 590 masuk
Batch 591 masuk
Batch 592 masuk
Batch 593 masuk
Batch 594 masuk
Batch 595 masuk
Batch 596 masuk
Batch 597 masuk
Batch 598 masuk
Batch 599 masuk
Batch 600 masuk
Batch 601 masuk
Batch 602 masuk
Batch 603 masuk
Batch 604 masuk
Batch 605 masuk
Batch 606 masuk
Batch 607 masuk
Batch 608 masuk
Batch 609 masuk
Batch 610 masuk
Batch 611 masuk
Batch 612 masuk
Batch 613 masuk
Batch 614 masuk
Batch 615 masuk
Batch 616 masuk
Batch 617 masuk
Batch 618 masuk
Batch 619 masuk
Batch 620 masuk
Batch 621 masuk
Batch 622 masuk
Batch 623 masuk
Batch 624 masuk
Batch 625 masuk
Batch 626 masuk
Batch 627 masuk
Batch 628 masuk
Batch 629 masuk
Batch 630 masuk
Batch 631 masuk
Batch 632 masuk
Batch 633 masuk
Batch 634 masuk
Batch 635 masuk
Batch 636 masuk
Batch 637 masuk
Batch 638 masuk
Batch 639 masuk
Batch 640 masuk
Batch 641 masuk
Batch 642 masuk
Batch 643 masuk
Batch 644 masuk
Batch 645 masuk
Batch 646 masuk
Batch 647 masuk
Batch 648 masuk
Batch 649 masuk
Batch 650 masuk
Batch 651 masuk
Batch 652 masuk
Batch 653 masuk
Batch 654 masuk
Batch 655 masuk
Batch 656 masuk
Batch 657 masuk
Batch 658 masuk
Batch 659 masuk
Batch 660 masuk
Batch 661 masuk
Batch 662 masuk
Batch 663 masuk
Batch 664 masuk
Batch 665 masuk
Batch 666 masuk
Batch 667 masuk
Batch 668 masuk
Batch 669 masuk
Batch 670 masuk
Batch 671 masuk
Batch 672 masuk
Batch 673 masuk
Batch 674 masuk
Batch 675 masuk
Batch 676 masuk
Batch 677 masuk
Batch 678 masuk
Batch 679 masuk
Batch 680 masuk
Batch 681 masuk
Batch 682 masuk
Batch 683 masuk
Batch 684 masuk
Batch 685 masuk
Batch 686 masuk
Batch 687 masuk
Batch 688 masuk
Batch 689 masuk
Batch 690 masuk
Batch 691 masuk
Batch 692 masuk
Batch 693 masuk
Batch 694 masuk
Batch 695 masuk
Batch 696 masuk
Batch 697 masuk
Batch 698 masuk
Batch 699 masuk
Batch 700 masuk
Batch 701 masuk
Batch 702 masuk
Batch 703 masuk
Batch 704 masuk
Batch 705 masuk
Batch 706 masuk
Batch 707 masuk
Batch 708 masuk
Batch 709 masuk
Batch 710 masuk
Batch 711 masuk
Batch 712 masuk
Batch 713 masuk
Batch 714 masuk
Batch 715 masuk
Batch 716 masuk
Batch 717 masuk
Batch 718 masuk
Batch 719 masuk
Batch 720 masuk
Batch 721 masuk
Batch 722 masuk
Batch 723 masuk
Batch 724 masuk
Batch 725 masuk
Batch 726 masuk
Batch 727 masuk
Batch 728 masuk
Batch 729 masuk
Batch 730 masuk
Batch 731 masuk
Batch 732 masuk
Batch 733 masuk
Batch 734 masuk
Batch 735 masuk
Batch 736 masuk
Batch 737 masuk
Batch 738 masuk
Batch 739 masuk
Batch 740 masuk
Batch 741 masuk
Batch 742 masuk
Batch 743 masuk
Batch 744 masuk
Batch 745 masuk
Batch 746 masuk
Batch 747 masuk
Batch 748 masuk
Batch 749 masuk
Batch 750 masuk
Batch 751 masuk
Batch 752 masuk
Batch 753 masuk
Batch 754 masuk
Batch 755 masuk
Batch 756 masuk
Batch 757 masuk
Batch 758 masuk
Batch 759 masuk
Batch 760 masuk
Batch 761 masuk
Batch 762 masuk
Batch 763 masuk
Batch 764 masuk
Batch 765 masuk
Batch 766 masuk
Batch 767 masuk
Batch 768 masuk
Batch 769 masuk
Batch 770 masuk
Batch 771 masuk
Batch 772 masuk
Batch 773 masuk
Batch 774 masuk
Batch 775 masuk
Batch 776 masuk
Batch 777 masuk
Batch 778 masuk
Batch 779 masuk
Batch 780 masuk
Batch 781 masuk
Batch 782 masuk
Batch 783 masuk
Batch 784 masuk
Batch 785 masuk
Batch 786 masuk
Batch 787 masuk
Batch 788 masuk
Batch 789 masuk
Batch 790 masuk
Batch 791 masuk
Batch 792 masuk
Batch 793 masuk
Batch 794 masuk
Batch 795 masuk
Batch 796 masuk
Batch 797 masuk
Batch 798 masuk
Batch 799 masuk
Batch 800 masuk
Batch 801 masuk
Batch 802 masuk
Batch 803 masuk
Batch 804 masuk
Batch 805 masuk
Batch 806 masuk
Batch 807 masuk
Batch 808 masuk
Batch 809 masuk
Batch 810 masuk
Batch 811 masuk
Batch 812 masuk
Batch 813 masuk
Batch 814 masuk
Batch 815 masuk
Batch 816 masuk
Batch 817 masuk
Batch 818 masuk
Batch 819 masuk
Batch 820 masuk
Batch 821 masuk
Batch 822 masuk
Batch 823 masuk
Batch 824 masuk
Batch 825 masuk
Batch 826 masuk
Batch 827 masuk
Batch 828 masuk
Batch 829 masuk
Batch 830 masuk
Batch 831 masuk
Batch 832 masuk
Batch 833 masuk
Batch 834 masuk
Batch 835 masuk
Batch 836 masuk
Batch 837 masuk
Batch 838 masuk
Batch 839 masuk
Batch 840 masuk
Batch 841 masuk
Batch 842 masuk
Batch 843 masuk
Batch 844 masuk
Batch 845 masuk
Batch 846 masuk
Batch 847 masuk
Batch 848 masuk
Batch 849 masuk
Batch 850 masuk
Batch 851 masuk
Batch 852 masuk
Batch 853 masuk
Batch 854 masuk
Batch 855 masuk
Batch 856 masuk
Batch 857 masuk
Batch 858 masuk
Batch 859 masuk
Batch 860 masuk
Batch 861 masuk
Batch 862 masuk
Batch 863 masuk
Batch 864 masuk
Batch 865 masuk
Batch 866 masuk
Batch 867 masuk
Batch 868 masuk
Batch 869 masuk
Batch 870 masuk
Batch 871 masuk
Batch 872 masuk
Batch 873 masuk
Batch 874 masuk
Batch 875 masuk
Batch 876 masuk
Batch 877 masuk
Batch 878 masuk
Batch 879 masuk
Batch 880 masuk
Batch 881 masuk
Batch 882 masuk
Batch 883 masuk
Batch 884 masuk
Batch 885 masuk
Batch 886 masuk
Batch 887 masuk
Batch 888 masuk
Batch 889 masuk
Batch 890 masuk
Batch 891 masuk
Batch 892 masuk
Batch 893 masuk
Batch 894 masuk
Batch 895 masuk
Batch 896 masuk
Batch 897 masuk
Batch 898 masuk
Batch 899 masuk
Batch 900 masuk
Batch 901 masuk
Batch 902 masuk
Batch 903 masuk
Batch 904 masuk
Batch 905 masuk
Batch 906 masuk
Batch 907 masuk
Batch 908 masuk
Batch 909 masuk
Batch 910 masuk
Batch 911 masuk
Batch 912 masuk
Batch 913 masuk
Batch 914 masuk
Batch 915 masuk
Batch 916 masuk
Batch 917 masuk
Batch 918 masuk
Batch 919 masuk
Batch 920 masuk
Batch 921 masuk
Batch 922 masuk
Batch 923 masuk
Batch 924 masuk
Batch 925 masuk
Batch 926 masuk
Batch 927 masuk
Batch 928 masuk
Batch 929 masuk
Batch 930 masuk
Batch 931 masuk
Batch 932 masuk
Batch 933 masuk
Batch 934 masuk
Batch 935 masuk
Batch 936 masuk
Batch 937 masuk
Batch 938 masuk
Batch 939 masuk
Batch 940 masuk
Batch 941 masuk
Batch 942 masuk
Batch 943 masuk
Batch 944 masuk
Batch 945 masuk
Batch 946 masuk
Batch 947 masuk
Batch 948 masuk
Batch 949 masuk
Batch 950 masuk
Batch 951 masuk
Batch 952 masuk
Batch 953 masuk
Batch 954 masuk
Batch 955 masuk
Batch 956 masuk
Batch 957 masuk
Batch 958 masuk
Batch 959 masuk
Batch 960 masuk
Batch 961 masuk
Batch 962 masuk
Batch 963 masuk
Batch 964 masuk
Batch 965 masuk
Batch 966 masuk
Batch 967 masuk
Batch 968 masuk
Batch 969 masuk
Batch 970 masuk
Batch 971 masuk
Batch 972 masuk
Batch 973 masuk
Batch 974 masuk
Batch 975 masuk
Batch 976 masuk
Batch 977 masuk
Batch 978 masuk
Batch 979 masuk
Batch 980 masuk
Batch 981 masuk
Batch 982 masuk
Batch 983 masuk
Batch 984 masuk
Batch 985 masuk
Batch 986 masuk
Batch 987 masuk
Batch 988 masuk
Batch 989 masuk
Batch 990 masuk
Batch 991 masuk
Batch 992 masuk
Batch 993 masuk
Batch 994 masuk
Batch 995 masuk
Batch 996 masuk
Batch 997 masuk
Batch 998 masuk
Batch 999 masuk
Batch 1000 masuk
Batch 1001 masuk
Batch 1002 masuk
Batch 1003 masuk
Batch 1004 masuk
Batch 1005 masuk
Batch 1006 masuk
Batch 1007 masuk
Batch 1008 masuk
Batch 1009 masuk
Batch 1010 masuk
Batch 1011 masuk
Batch 1012 masuk
Batch 1013 masuk
Batch 1014 masuk
Batch 1015 masuk
Batch 1016 masuk
Batch 1017 masuk
Batch 1018 masuk
Batch 1019 masuk
Batch 1020 masuk
Batch 1021 masuk
Batch 1022 masuk
Batch 1023 masuk
Batch 1024 masuk
Batch 1025 masuk
Batch 1026 masuk
Batch 1027 masuk
Batch 1028 masuk
Batch 1029 masuk
Batch 1030 masuk
Batch 1031 masuk
Batch 1032 masuk
Batch 1033 masuk
Batch 1034 masuk
Batch 1035 masuk
Batch 1036 masuk
Batch 1037 masuk
Batch 1038 masuk
Batch 1039 masuk
Batch 1040 masuk
Batch 1041 masuk
Batch 1042 masuk
Batch 1043 masuk
Batch 1044 masuk
Batch 1045 masuk
Batch 1046 masuk
Batch 1047 masuk
Batch 1048 masuk
Batch 1049 masuk
Batch 1050 masuk
Batch 1051 masuk
Batch 1052 masuk
Batch 1053 masuk
Batch 1054 masuk
Batch 1055 masuk
Batch 1056 masuk
Batch 1057 masuk
Batch 1058 masuk
Batch 1059 masuk
Batch 1060 masuk
Batch 1061 masuk
Batch 1062 masuk
Batch 1063 masuk
Batch 1064 masuk
Batch 1065 masuk
Batch 1066 masuk
Batch 1067 masuk
Batch 1068 masuk
Batch 1069 masuk
Batch 1070 masuk
Batch 1071 masuk
Batch 1072 masuk
Batch 1073 masuk
Batch 1074 masuk
Batch 1075 masuk
Batch 1076 masuk
Batch 1077 masuk
Batch 1078 masuk
Batch 1079 masuk
Batch 1080 masuk
Batch 1081 masuk
Batch 1082 masuk
Batch 1083 masuk
Batch 1084 masuk
Batch 1085 masuk
Batch 1086 masuk
Batch 1087 masuk
Batch 1088 masuk
Batch 1089 masuk
Batch 1090 masuk
Batch 1091 masuk
Batch 1092 masuk
Batch 1093 masuk
Batch 1094 masuk
Batch 1095 masuk
Batch 1096 masuk
Batch 1097 masuk
Batch 1098 masuk
Batch 1099 masuk
Batch 1100 masuk
Batch 1101 masuk
Batch 1102 masuk
Batch 1103 masuk
Batch 1104 masuk
Batch 1105 masuk
Batch 1106 masuk
Batch 1107 masuk
Batch 1108 masuk
Batch 1109 masuk
Batch 1110 masuk
Batch 1111 masuk
Batch 1112 masuk
Batch 1113 masuk
Batch 1114 masuk
Batch 1115 masuk
Batch 1116 masuk
Batch 1117 masuk
Batch 1118 masuk
Batch 1119 masuk
Batch 1120 masuk
Batch 1121 masuk
Batch 1122 masuk
Batch 1123 masuk
Batch 1124 masuk
Batch 1125 masuk
Batch 1126 masuk
Batch 1127 masuk
Batch 1128 masuk
Batch 1129 masuk
Batch 1130 masuk
Batch 1131 masuk
Batch 1132 masuk
Batch 1133 masuk
Batch 1134 masuk
Batch 1135 masuk
Batch 1136 masuk
Batch 1137 masuk
Batch 1138 masuk
Batch 1139 masuk
Batch 1140 masuk
Batch 1141 masuk
Batch 1142 masuk
Batch 1143 masuk
Batch 1144 masuk
Batch 1145 masuk
Batch 1146 masuk
Batch 1147 masuk
Batch 1148 masuk
Batch 1149 masuk
Batch 1150 masuk
Batch 1151 masuk
Batch 1152 masuk
Batch 1153 masuk
Batch 1154 masuk
Batch 1155 masuk
Batch 1156 masuk
Batch 1157 masuk
Batch 1158 masuk
Batch 1159 masuk
Batch 1160 masuk
Batch 1161 masuk
Batch 1162 masuk
Batch 1163 masuk
Batch 1164 masuk
Batch 1165 masuk
Batch 1166 masuk
Batch 1167 masuk
Batch 1168 masuk
Batch 1169 masuk
Batch 1170 masuk
Batch 1171 masuk
Batch 1172 masuk
Batch 1173 masuk
Batch 1174 masuk
Batch 1175 masuk
Batch 1176 masuk
Batch 1177 masuk
Batch 1178 masuk
Batch 1179 masuk
Batch 1180 masuk
Batch 1181 masuk
Batch 1182 masuk
Batch 1183 masuk
Batch 1184 masuk
Batch 1185 masuk
Batch 1186 masuk
Batch 1187 masuk
Batch 1188 masuk
Batch 1189 masuk
Batch 1190 masuk
Batch 1191 masuk
Batch 1192 masuk
Batch 1193 masuk
Batch 1194 masuk
Batch 1195 masuk
Batch 1196 masuk
Batch 1197 masuk
Batch 1198 masuk
Batch 1199 masuk
Batch 1200 masuk
Batch 1201 masuk
Batch 1202 masuk
Batch 1203 masuk
Batch 1204 masuk
Batch 1205 masuk
Batch 1206 masuk
Batch 1207 masuk
Batch 1208 masuk
Batch 1209 masuk
Batch 1210 masuk
Batch 1211 masuk
Batch 1212 masuk
Batch 1213 masuk
Batch 1214 masuk
Batch 1215 masuk
Batch 1216 masuk
Batch 1217 masuk
Batch 1218 masuk
Batch 1219 masuk
Batch 1220 masuk
Batch 1221 masuk
Batch 1222 masuk
Batch 1223 masuk
Batch 1224 masuk
Batch 1225 masuk
Batch 1226 masuk
Batch 1227 masuk
Batch 1228 masuk
Batch 1229 masuk
Batch 1230 masuk
Batch 1231 masuk
Batch 1232 masuk
Batch 1233 masuk
Batch 1234 masuk
Batch 1235 masuk
Batch 1236 masuk
Batch 1237 masuk
Batch 1238 masuk
Batch 1239 masuk
Batch 1240 masuk
Batch 1241 masuk

C:\Users\calys\AppData\Local\Temp\ipykernel_21512\2436008270.py:10: LangChainDeprecationWarning: Since Chroma 0.4.x the manual persistence method is no longer supported as docs are automatically persisted.
  vectorstore.persist()

In [16]:
query = "gempa besar di Indonesia tahun 2022"
docs = vectorstore.similarity_search(query, k=3)

for d in docs:
    print(d.page_content)
    print(d.metadata)
    print("----")

Pada tanggal 25 March 2000 pukul 00:00 WIB terjadi gempa bumi di Provinsi Bali dengan magnitudo 4.9 dan kedalaman 2.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -8.2032 dan bujur 114.821.
{'year': 2000, 'depth_category': 'dangkal', 'date': '3/25/2000', 'province': 'Bali', 'magnitude': 4.9, 'month': 3}
----
Pada tanggal 26 June 2001 pukul 00:00 WIB terjadi gempa bumi di Provinsi Bali dengan magnitudo 4.7 dan kedalaman 2.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -7.614 dan bujur 114.907.
{'month': 6, 'date': '6/26/2001', 'depth_category': 'dangkal', 'magnitude': 4.7, 'year': 2001, 'province': 'Bali'}
----
Pada tanggal 22 January 2016 pukul 00:00 WIB terjadi gempa bumi di Provinsi Bali dengan magnitudo 2.2 dan kedalaman 10.0 km. Gempa ini termasuk gempa dangkal dan berlokasi pada koordinat lintang -8.2 dan bujur 115.35.
{'year': 2016, 'date': '1/22/2016', 'month': 1, 'depth_category': 'dangkal', 'province': 'Bali', 'magnitude': 2.2}
----